version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php-apache2
            dockerfile: Dockerfile
        depends_on:
          - db
        volumes:
            - ./sources/:/var/www/html/
        ports:
            - 8000:80
            
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: web
            MYSQL_USER: root2
            MYSQL_PASSWORD: 12345
        ports:
            - "9906:3306"
        volumes: 
            - ./sources/database/data2.sql:/docker-entrypoint-initdb.d/dump.sql
